#
# GitLab CI/CD configuration
#


include:
  - component: $CI_SERVER_FQDN/tech_team/ci/autocompliance/autocompliance@~latest
  - component: $CI_SERVER_FQDN/tech_team/ci/secrets-detection/secrets-detection@~latest
  - component: $CI_SERVER_FQDN/tech_team/ci/trust/trust@~latest


default:
  interruptible: true


.container_builds:
  stage: build
  trigger:
    include: .gitlab/templates/build_container.yml
    forward:
      yaml_variables: true
      pipeline_variables: true
    strategy: depend


alpine321-buildenv:
  variables:
    DESTINATION: $CI_REGISTRY_IMAGE/alpine321-buildenv
    DOCKERFILE: ./images/alpine321-buildenv/Dockerfile
    TAG: "$CI_COMMIT_BRANCH"
    BASE_IMAGE_TAG: "1.0.0"
  extends: .container_builds


alpine321:
  stage: build
  image: $CI_REGISTRY_IMAGE/alpine321-buildenv:$CI_COMMIT_BRANCH
  needs: [ alpine321-buildenv ]
  script:
    - source "${HOME}/.cargo/env"
    - cargo --version
    - cargo build --release


ubuntu2204-buildenv:
  variables:
    DESTINATION: $CI_REGISTRY_IMAGE/ubuntu2204-buildenv
    DOCKERFILE: ./images/ubuntu2204-buildenv/Dockerfile
    TAG: "$CI_COMMIT_BRANCH"
    BASE_IMAGE_TAG: "1.4.0"
  extends: .container_builds


ubuntu2204:
  stage: build
  image: $CI_REGISTRY_IMAGE/ubuntu2204-buildenv:$CI_COMMIT_BRANCH
  needs: [ ubuntu2204-buildenv ]
  script:
    - source "${HOME}/.cargo/env"
    - cargo build --release

