#
#  Alpine 3.21 build environment for 'trust'
#


FROM dmz-gitlab.honda-ri.de:5050/tech_team/docker/alpine321-hri-rustc:56-AlpineLinux

#USER root

#RUN RUN apk --no-cache --no-check-certificate --allow-untrusted add cargo

#USER hri


# EOF
